### ISSUE TITLE
Latest versions don't install PKGs in a DMG

### ISSUE THREAD

**Issue by colinbennett** [henri/installpkg#1]
Hi. I've used v0.1.3 for a long time and it has worked great. I use installpkg to batch install the audio plug-ins from Sinevibes. The plug-ins come as DMGs with an installer PKG and/or PDF or WebArchive inside. I use sudo installpkg -i /DirectoryWithDMGs/\* 

v0.1.3 installs them totally fine but v0.1.7 doesn't recognize the PKGs inside the package. I'm not sure what has changed with v0.1.7 but it might be worth looking into.

For example. v0.1.3 works great for every DMG in the folder (1 output below):

iMac:~ Mac$ sudo installpkg -i /Users/Mac/Desktop/Test/*
Password:

Mounting Item : /Users/Mac/Desktop/Test/Drift200.dmg
Installing Item : /Volumes/Drift/Drift 2.0.0.pkg
installer: Package name is Sinevibes Drift 2.0.0
installer: Upgrading at base path /
installer: The upgrade was successful.
WARNING! : Item is not a package : /Volumes/Drift/Drift.pdf
           Item has not been installed
Item unmounted.

But v0.1.7 totally freaks with every DMG in the folder (1 output below).

iMac:~ Mac$ sudo installpkg -i /Users/Mac/Desktop/Test/*

Mounting Item : /Users/Mac/Desktop/Test/Drift200.dmg
WARNING! : Item is not a package and has not been installed : /tmp/installpkg_mountpoints//Volumes/Drift/*
hdiutil: detach failed - No such file or directory
hdiutil: detach failed - No such file or directory
WARNING! : Unable to unmount item : /tmp/installpkg_mountpoints//Volumes/Drift

Hopefully this can be fixed. Thanks!

**Comment by henri** [comment]
Would you kindly try using installpkg v0.1.9 or later and report back if you have any further issues : http://lucid.technology/download/installpkg
