### ISSUE TITLE
how do you uninstall/clean up installpkg's installation?

### ISSUE THREAD

**Issue by msphair** [henri/installpkg#2]

**Comment by henri** [comment]
There is a BASH script ([link to source on GitHub](https://github.com/henri/installpkg/blob/master/install_components/InstallPKG-Uninstall.bash)) called "InstallPKG-Uninstall.bash". This is bundled within the disk image ([download link](http://www.lucid.technology/download/installpkg)) for InstallPKG . Running this script will uninstall installpkg and any related files from the host system.

Below are step by step instructions for removal of installpkg from your system using this script. The instructions assume that you have wget installed on your system. If you do not have this installed, then you will need to manually download the "InstallPKG-Uninstall.bash" into the `/tmp` directory on your system and then skip step number two below. Note, all commands should be run as root.
1. `cd /tmpwget`
2. `wget http://lucid.technology/download/installpkg/uninstall-script -O InstallPKG-Uninstall.bash`
3. `chmod 755 ./InstallPKG-Uninstall.bash`
4. `./InstallPKG-Uninstall.bash`
5. `echo $?`

If you have any questions or problems, let me know.

**Comment by henri** [comment]
Also, if you are looking to auto remove installpkg (if it is not installed) as part of another system, you may wish to take a look at [this example script](https://github.com/henri/printer-setup/blob/master/ExampleFiles/Deployment/PrinterSetup_OSX_PACKAGE/PrinterSetupPackage.sh).
