### ISSUE TITLE
AutoPKG

### ISSUE THREAD

**Issue by morgrowe** [henri/installpkg#4]
Hi there,

I'd like to start by thanking you for your work on InstallPKG. It's an absolute god-send when trying to install all of the GarageBand loops on multiple machines.

I'm trying to write an AutoPKG recipe that will fetch the latest version of your software an offer it through AutoPKG. However, in order to do this, you'd need to make a small change to your latest release. Correct me if I'm wrong, but you seem to be releasing your software as only archives rather than archives and a release? The processor I'm trying to use to automatically grab your latest release doesn't understand archives.

For example, the link to 0.3.2 is https://github.com/henri/installpkg/archive/0.3.2.zip whereas, the latest version of BitBar and many other projects are available via these sorts of links https://github.com/matryer/bitbar/releases/download/v1.9.2/BitBar-v1.9.2.zip, which the AutoPKG processor understands.

If you wouldn't mind offering your latest version (only the latest, no need to back through them all) as a release as well as an archive that would be great. If not, not to worry, I'm still more than happy coming over here and manually grabbing the latest version. :)

Many thanks
Morgan

**Comment by henri** [comment]
To pull down the latest version of InstallPKG visit : http://lucid.systems/download/installpkg

The URL above points to the latest version of InstallPKG. Glad to know InstallPKG is helping you out. If this is not solving the issue relating to sucking down the latest version, then just let me know. Hope this helps!

**Comment by morgrowe** [comment]
Yup, using that link does the job. Thank you.

**Comment by henri** [comment]
Great!
