### ISSUE TITLE
Feature request - handle common .dmg tree variations

### ISSUE THREAD

**Issue by will-riley** [henri/installpkg#5]
Many installer .dmg files put the .app at the root level. Perhaps it would be more useful to copy that to /Applications if it exists than pass over it. Same for the Documentation pdfs, extras dirs etc. A flag to transfer all of that into an app-named folder in /Applications instead of just issuing a warning it would be awesome!

**Comment by henri** [comment]
Perhaps you could outline in more detail what you are seeking. At this stage installpkg is focused on dealing with making the installation of multiple .pkg files as easy as possible. You may want to take a look at autopkg? It is possible that I have misunderstood your request for support of .app files and support files. Please clarify that you are requesting the .App file is able to be copied to the /Applications folder and that also any supporting documents are also copied to /Applications folder.

Installpkg is open source you we welcome to modify it to meet you needs and if you like you are also welcome to submit a pull request. I am doing my best to understand your suggestion. It is great that you like installpkg thanks for opening an feature request. Please clarify that I have understood what you are trying to do is pull .App files from a disk image and put them into the /Applications folder?

**Comment by henri** [comment]
Also, just as another suggestion. If the program you are looking to install is supported by home-brew. This could be another way of installing the program. Check out HomeBrew : https://brew.sh

If you are still after this feature, then do let me know. But this is not really a specific use case for this application at this time. Certainly, not a priority. We will consider pull requests if you do add this feature.
