### ISSUE TITLE
How to use -allowUntrusted?

### ISSUE THREAD

**Issue by ignaciosot** [henri/installpkg#7]
Noob question here, how should I use the -allowUntrusted flag?

right now if I run installpkg -allowUntrusted /Volumes/FakeVolume/Folderwithinstallers/*

I get: ERROR! : The -e flag is not compatible with the -u flag.

**Comment by henri** [comment]
Hello,

Not sure about the -allowUntrusted argument. Is this something you have added? Perhaps you are not using the offical build : http://www.lucid.technology/tools/installpkg

If you run the following command you will have the manual for installing : 
`man installpkg`

This will give you the flag summary : 

 _Flag summary :
        -i       install from disk image
        -h       hide mount point of disk iamge (only works with the -i flag)
        -u       install from URL
        -c       copy to local storage before installing (incompatible with -u
       flag)
        -e       eject source volume mode (incompatible with -u flag)
        -v       verbose mode (more verbose)
        -q       quiet output (less verbose)_


You will see that -u is for installing from a URL (for example) when you update installpkg you could use the command : 
installpkg -iuh http://lucid.systems/download/installpkg

Also, the reason that -u and -e are incompatible is that it is not possible to eject install media if you are downloading the package from a URL. Hope that makes sense.

Perhaps you can explain a little more about the untrusted command you are trying to run.
Thanks.
Henri

**Comment by ignaciosot** [comment]
Sorry I wasn't specific.

When I tried to install a .pkg that had an expired or untrusted certificate I would get

```
installer: Package name is Fake Software
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
    WARNING! : Errors were encountered during installation of package : /Path/FakeSoftware.pkg
----------------------------------------------------------------------------
Summary : 

    ERROR! : No packages (.pkg or .mpkg) or images (.dmg) were installed.


    WARNING : [1] packages or images failed installation.
```
I solved it by changing line 149 of the file "installpkg" under /usr/local/bin/installpkg to this:

```
        sudo installer -pkg "${item2add}" -target / -allowUntrusted
```

**Comment by henri** [comment]
Glad you have a work around 👍 :) Do keep in mind that this modification will have some security implications.
